name: Create release on Pull Request merged
"on":
  pull_request:
    types: [closed]

jobs:
  create_release:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create Release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.event.issue.pull_request.head.ref }}
          body: |
            ${{ github.event.issue.pull_request.head.repo.description }}
          draft: false
          prerelease: false
