name: Deploy to Preview Channel
"on":
  issue_comment:
    types: [created]

jobs:
  buid_deploy_and_preview:
    if: contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          CI: false
      - name: Deploy to Preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOC_HOANG_WEBPAGE }}"
          projectId: loc-hoang-webpage
          expires: 7d
          entryPoint: "./frontend"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
