name: Deploy to Preview Channel
"on":
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: check comment
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/preview"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
  buid_deploy_and_preview:
    runs-on: ubuntu-latest
    needs: deploy-check
    if: needs.deploy-check.outputs.triggered == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          CI: false
      - name: Deploy to Preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOC_HOANG_WEBPAGE }}"
          projectId: loc-hoang-webpage
          expires: 7d
          entryPoint: "./frontend"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
