name: Deploy to Live Channel
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          CI: false
      - name: Deploy to Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOC_HOANG_WEBPAGE }}"
          channelId: live
          projectId: loc-hoang-webpage
          entryPoint: "./frontend"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
